### ISSUE TITLE
Can't find matlab when a user root dir is specified

### ISSUE THREAD

**Issue by CarloNicolini** [audiofilter/mex-it#1]
It seems that the script can't detect the matlab folder that is in my home:

/home/carlo/MATHWORKS

inside that folder I've the installation of my matlabR2013a on Ubuntu 14.04 x86_64
Specifying 

cmake -DMatlab_USER_ROOT=/home/carlo/MATHWORKS .

doesn't work either.

The content of that folder is this:
appdata  bin  etc  extern  help  java  licenses  license.txt  mcr  patents.txt  resources  runtime  simulink  sys  toolbox  trademarks.txt  X11

**Comment by audiofilter** [comment]
I will take a look at Cmake finding matlab that is not installed in a typical place for Ubuntu, although I don't have access to an Ubuntu with Matlab installed at the moment. The FindMatlab.cmake was not originally written by me, but it also states that "matlab" must be on your Path. I guess that would be /home/carlo/MATHWORKS/bin in your case.

**Comment by audiofilter** [comment]
Is this still an issue?

**Comment by CarloNicolini** [comment]
No it's not an issue now.
I've explicityl added into the PATH the /home/carlo/MATHWORKS/bin folder
where the matlab executable stays.

Thanks!


2015-04-17 3:04 GMT+02:00 Audio Filter <notifications@github.com>:
